chat/urls.py
from django.contrib import admin
from django.urls import path, include

from chat.views import HomePage, TwitteCreate, FollowView

urlpatterns = [
    path('', HomePage.as_view(), name="home"),
    path('twitte/', TwitteCreate.as_view(), name="twitte"),
    path('follow/', FollowView.as_view(), name="follow"),

]

twitter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include(('chat.urls', 'chat'), namespace='chat'))
]

chat/models.py
from django.contrib.auth.models import User
from django.db import models


class Twitte(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    text = models.CharField(max_length=140, null=True, blank=True)
    created_ts = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    twitte = models.ForeignKey(Twitte, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.user.username + "--------" +self.twitte.text

chat/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, View
from django import forms

from chat.models import Twitte, Follow


class TwitteCreateForm(forms.ModelForm):

    class Meta:
        fields = ['text']
        model = Twitte


class HomePage(LoginRequiredMixin, ListView):
    model = Twitte
    template_name = 'home.html'
    login_url = reverse_lazy('login')


class TwitteCreate(LoginRequiredMixin, CreateView):
    model = Twitte
    form_class = TwitteCreateForm
    template_name = 'create.html'
    success_url = reverse_lazy('chat:home')
    
    def get_context_data(self, **kwargs):
        return super(TwitteCreate, self).get_context_data(**kwargs)
    
    def form_valid(self, form):
        if form.is_valid():
            form.instance.user = self.request.user
            form.save()
            return HttpResponseRedirect(self.success_url)
        else:
            return super().form_valid(form)


class FollowView(LoginRequiredMixin, View):

    def get(self, request):
        twitte_id = self.request.GET.get('twitte_id')
        twitte = Twitte.objects.filter(id=twitte_id).first()
        if not Follow.objects.filter(twitte=twitte, user=self.request.user).exists():
            Follow.objects.create(twitte=twitte, user=self.request.user)
        return HttpResponseRedirect(reverse('chat:home'))

chat/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'chat:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      {% if not user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      {% endif %}
      {% if user.is_authenticated %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'chat:twitte' %}">Twitte</a>
        </li>
        <li class="nav-item">
          <strong><a class="nav-link" >{{user.username}}</a></strong>
        </li>
      {% endif %}
    </ul>

  </div>
</nav>
    {% block container %}
    {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

chat/templates/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags  %}

{% block container %}
  <div class="container">
      <div class="row">
          <div class="col">
              <form method="post">
                  {% csrf_token %}
                  {{ form|crispy }}
                  <button class="btn btn-success" type="submit">Twitte</button>
              </form>
          </div>
      </div>
</div>

{% endblock %}


chat/templates/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags  %}

{% block container %}
  <div class="container">
      <div class="row">
          <div class="col">
              <table class="table">
                <thead>
                    <tr>
                        <th>User</th>
                        <th>Message</th>
                    </tr>
                </thead>
                <tbody>
                    {% for obj in object_list %}
                        <tr>
                            <td>{{obj.user.username}}</td>
                            <td>{{obj.text}}</td>
                            <td>
                                {% if user != obj.user %}
                                    <a class="btn btn-primary" href="{% url 'chat:follow' %}?twitte_id={{obj.id}}">Follow</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
                </table>
          </div>
      </div>
</div>

{% endblock %}
